defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: atos
- graph: encoder_decoder_only
- model: transformer
- training: default
- _self_

config_validation: False

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

diagnostics:
  log:
    mlflow:
      enabled: True
      offline: False
      terminal: True
hardware:
  accelerator: auto
  num_nodes: 1
  num_gpus_per_model: 1


model:
  num_channels: 1024
dataloader:
  limit_batches:
    training: null
    validation: 100

training:
  max_epochs: 2
  max_steps: 300
  lr:
    rate: 6.25e-5 # tests
    iterations: 300000
    min: 3e-7 #Not scaled by #GPU